services:
  laravel-app:
    build: .
    container_name: laravel-app
    ports:
      - "8000:8000" # HTTP
      - "5173:5173"
    volumes:
      - ./:/var/www
      - vendor_data:/var/www/vendor
      - node_data:/var/www/node_modules
    tty: true
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  vendor_data:
  node_data:
  db_data:


