version: "3.8"

services:
  laravel-app:
    build: .
    container_name: laravel-app
    ports:
      - "8000:8000" # HTTP
      - "5173:5173"
    volumes:
      - ./:/var/www
    tty: true
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"

volumes:
  db_data:


